### PR TITLE
Follow CNAME records for DNS challenge

### PR DESCRIPTION
**Pull request by andrewda**
The ACME protocol allows CNAMEs from `_acme-challenge` subdomains to domains with the proper challenge tokens. For example, the following configuration would be valid:

```
_acme-challenge.example.com		CNAME	test1.example.com.
test1.example.com				TXT		srFQeeM4d8iP7FpzGcxrc4mmRtKdJ_uJJBo5DlWHYSs
```

Pebble should abide by this by following CNAME records and reading any TXT records from the target domain.

This feature is used extensively by tools such as https://github.com/joohoi/acme-dns.

### CODE REVIEW

**Comment by felixfontein** [comment]
Hmm, is this actually necessary? The documentation of `getTXTEntry` says:
```
// getTXTEntry fetches TXT entries for the given domain name using the recursive resolver located at
// `va.customResolverAddr`, or the default system resolver if no custom resolver addr is specified
```
So it assumes that the custom resolver is a *recursive* resolver, and that one is supposed to follow CNAMEs automatically.

**Comment by felixfontein** [comment]
Also, it looks like CI is currently broken (independent of this PR): certbot seems to no longer support Python 3.5 and 2.7, and that seem to be the Python versions available in CI.

**Comment by andrewda** [comment]
You're likely correct for a production setup, but many test/local DNS servers don't have recursive capabilities. Specifically, my testing setup uses `dnsmasq` and https://github.com/joohoi/acme-dns -- `dnsmasq` to create the CNAME records and `acme-dns` as a nameserver to resolve the TXT records. `dnsmasq` doesn't resolve recursively, so the TXT records are never found by pebble, unless something like this is added.

I might try replacing `dnsmasq` with Unbound or BIND to see if I can get either of those to work recursively.

**Comment by jsha** [comment]
I think replacing `dnsmasq` with Unbound or BIND in your test setup is the right move here. Unbound is pretty easy to set up! If you don't like the packaged version provided by your OS, I have a very small config for a standalone user-mode unbound as part of unboundtest: https://github.com/jsha/unboundtest

**Comment by jsha** [comment]
Closing. As discussed above, we shouldn't implement CNAME chasing in Pebble. That's the recursive resolver's job.

**Pull request closed without merging**
