### PR TITLE
db: missing authz rlock in FindValidAuthorization

### PR DESCRIPTION
**Pull request by alexzorin**
Fixes the race reported in #268

### CODE REVIEW

**Comment by alexzorin** [comment]
On reflection, I don't think adding more granular locks is the right fix. After all, this function already held a read lock on the MemoryStore.

Seems like the actual problem is that MemoryStore is handing out mutable pointers to its underlying data and then some code (like `va.setAuthzInvalid`) is abusing that fact.

Uh oh!

**Comment by cpu** [comment]
> Seems like the actual problem is that MemoryStore is handing out mutable pointers to its underlying data and then some code (like va.setAuthzInvalid) is abusing that fact.

:sweat: I think the slap dash parts of Pebble we threw together at the start to bootstrap the Boulder ACME v2 work are starting to show their age/limited design thought.

> On reflection, I don't think adding more granular locks is the right fix. After all, this function already held a read lock on the MemoryStore.

Agreed. I think more subtantial rework is probably required. I'm hoping to have a chance to pivot to more substantial Pebble work in ~Sept. On the top of my list was more comprehensive tests. I think addressing the memorystore hack is another priority. 

I think I'd be willing to swallow the cost of a new dependency to gain a more robust in-memory database implementation (it would also knock out the many O(N) query operations), maybe something like https://github.com/hashicorp/go-memdb My primary criteria is avoiding persistence/durability.

WDYT?

**Comment by alexzorin** [comment]
I think MemoryStore could be reworked by banning pointers and requiring everything to be passed around by value. That should allow us to eliminate all of the locks except a single RW lock on the store, right?

go-memdb [would appear to be](https://play.golang.org/p/VZLk3QLFrdq) a sidegrade from that perspective - the same pitfall with leaky pointers exists there.

I don't have any strong feelings about fixing the O(N) scans. Seems like it's not something that would matter for a few hundred slice elements, but tbh even the addition of `ordersByAccountID` in #260 seemed like an unnecessary optimization to me.

**Comment by cpu** [comment]
>  go-memdb would appear to be a sidegrade from that perspective - the same pitfall with leaky pointers exists there.

Agreed, I think either with the existing memstore or an alternative library we would have to switch to passing things around by value.

>  I don't have any strong feelings about fixing the O(N) scans

Me either. Certainly not a big priority given Pebble's explicit use cases.

> Edit: Now that I think about it, proper transactions are probably going to be required if doing pass-by-value.

This was my thought too. We could switch the existing memstore around to pass by value but without transactions I think there will be some weird inconsistencies made possible (maybe that doesn't matter that much?) with `go-memdb` we could use transactions and avoid that.

I'm interested in hearing what @jsha thinks. Historically he's been able to convince me I'm overthinking things with good regularity :laughing: He's OOO this week but will be back next week. It's unlikely I'll start moving on any of this before then.

**Comment by jsha** [comment]
We talked about this by voice; sorry I forgot to update here. I think pass-by-value is fine, since all we expect to return for a given HTTP request is a snapshot of an object's state at a point in time. If that state happened to change while the HTTP request was inflight, no big deal; the next polling request or the next attempt to update the object will get the updated value.

Note that rewriting everything to be pass-by-value would be pretty annoying, because it means a lot of places that `return nil, err` would have to be rewritten as `return SomeType{}, err`. Instead I think it makes sense to give each relevant type a `.clone()` method and return that, or just use [`reflect.Copy()`](https://golang.org/pkg/reflect/#Copy).

**Pull request closed without merging**
