### PR TITLE
GolangCI-Lint Fixes

### PR DESCRIPTION
**Pull request by sheurich**
This PR addresses https://github.com/letsencrypt/pebble/issues/438 by fixing all of the reported issues in Pebble code.

When run with the default lint configuration, golangci-lint reports:
```plain
wfe/wfe.go:2365:2: S1017: should replace this `if` statement with an unconditional `strings.TrimPrefix` (gosimple)
        if strings.HasPrefix(ident.Value, "*.") {
        ^
wfe/wfe.go:1443:32: S1039: unnecessary use of fmt.Sprintf (gosimple)
                return acme.MalformedProblem(fmt.Sprintf(
                                             ^
wfe/wfe.go:1405:2: SA5011: possible nil pointer dereference (staticcheck)
        order.RLock()
        ^
wfe/wfe.go:1409:5: SA5011(related information): this check suggests that the pointer can be nil (staticcheck)
        if order == nil {
           ^
wfe/wfe.go:1406:8: SA5011: possible nil pointer dereference (staticcheck)
        defer order.RUnlock()
              ^
wfe/wfe.go:181:2: SA1019: rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: As of Go 1.20 there is no reason to call Seed with a random value. Programs that call Seed with a known value to get a specific sequence of results should use New(NewSource(seed)) to obtain a local random generator. (staticcheck)
        rand.Seed(time.Now().UnixNano())
        ^
va/va.go:321:10: S1039: unnecessary use of fmt.Sprintf (gosimple)
                msg := fmt.Sprintf("No TXT records found for DNS challenge")
                       ^
va/va.go:338:9: S1039: unnecessary use of fmt.Sprintf (gosimple)
        msg := fmt.Sprintf("Correct value not found for DNS challenge")
               ^

wfe/wfe.go:178: File is not `gofumpt`-ed (gofumpt)
        strict, requireEAB bool, retryAfterAuthz int, retryAfterOrder int) WebFrontEndImpl {
```

These errors are addressed here.

Other fixes include:
- A fix for a WFE panic: [Use built-in UTC for TZ to eliminate panics](https://github.com/letsencrypt/pebble/pull/439/commits/2ee3d6bde0450bb9edc7790f0d04d9fc3bae8577)
- Fixes for Appveyor and Travis related to Python
- Update golanci-lint to current in Travis

### CODE REVIEW

**Comment by sheurich** [comment]
I've identified a concurrency race condition related to this patch and will be providing a fix shortly:
```plain
WARNING: DATA RACE
Read at 0x00c000110000 by goroutine 250:
  math/rand.(*rngSource).Uint64()
  math/rand.(*rngSource).Int63()
  math/rand.(*Rand).Int63()
  math/rand.(*Rand).Int31()
  math/rand.(*Rand).Int31n()
  math/rand.(*Rand).Intn()
  github.com/letsencrypt/pebble/v2/wfe.(*WebFrontEndImpl).verifyJWS()
  github.com/letsencrypt/pebble/v2/wfe.(*WebFrontEndImpl).verifyPOST()
  github.com/letsencrypt/pebble/v2/wfe.(*WebFrontEndImpl).Authz()
```

**Comment by sheurich** [comment]
Corrected the race condition in [`fd2b2be` (#439)](https://github.com/letsencrypt/pebble/pull/439/commits/fd2b2beaa84994e05329099ed1e4bca348ae9865). This change is ready for review.

**Review by aarongable — APPROVED** [review]
Go code changes LGTM. Travis / Appveyor changes seem reasonable but I know nothing about those systems and with https://github.com/letsencrypt/pebble/pull/442 it looks like we're heading towards getting rid of them.

**Comment by sheurich** [comment]
@aarongable this change is ready for re-approval after merging main.

**Review by mcpherrinm — APPROVED** [review]

**Pull request merged**
