### PR TITLE
Use snap instead of certbot-auto in travis CI

### LINKED ISSUE #354: Travis relies on certbot-auto causing Travis to fail
It seems the Travis CI uses the deprecated `certbot-auto` command:

However, as we all know, `certbot-auto` has been [deprecated](https://github.com/certbot/certbot/pull/8489) and consequently [removed](https://github.com/certbot/certbot/pull/8938). This causes Travis to fail:

```
$ git clone --single-branch --depth=1 -b master https://github.com/certbot/certbot
$ cd certbot
$ ./certbot-auto --os-packages-only -n
/home/travis/.travis/functions: line 109: ./certbot-auto: No such file or directory
The command "./certbot-auto --os-packages-only -n" failed and exited with 127 during .
```

### PR DESCRIPTION
**Pull request by aarongable**
Fixes #354

### CODE REVIEW

**Comment by aarongable** [comment]
Looks like this fixes the certbot install issue, but it also looks like a side-effect of that certbot installation method was activating the certbot python venv, which was indirectly providing the josepy package for chisel2.py to use.

**Comment by osirisinferi** [comment]
> it also looks like a side-effect of that certbot installation method was activating the certbot python venv, which was indirectly providing the josepy package for chisel2.py to use.

Can't you just do a `apt-get install python3-josepy` for that?

**Comment by aarongable** [comment]
That was a good idea, but looks like chisel2.py actually relies on the entirety of the `acme` python library... which is part of the certbot repo. So I guess I'm gonna do both: install certbot from snap, *and* clone the certbot repo and activate its venv.

**Comment by osirisinferi** [comment]
> So I guess I'm gonna do both: install certbot from snap, _and_ clone the certbot repo and activate its venv.

I don't know which distribution Travis is running on, but I think Debian and Ubuntu both also have a package python3-acme :stuck_out_tongue: But I guess just pulling the git repo works too :wink: Don't know which is quicker/easier tho.

**Comment by aarongable** [comment]
Ooh interesting, I didn't expect that! Giving it a shot, thanks.

**Comment by osirisinferi** [comment]
Huh, and suddenly you don't need augeas any longer? How does that compute? :stuck_out_tongue: Ah well, the checks have passed :grin:

**Review by beautifulentropy — APPROVED** [review]

**Pull request merged**
