### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by felixfontein**

### CODE REVIEW

**Comment by felixfontein** [comment]
Replacing Ubuntu 16.04 (which has Python 2.7 and 3.5, which are not supported by Certbot anymore) by Ubuntu 20.04. Also replacing venv3 → venv.

**Comment by felixfontein** [comment]
Restarting travis.

**Comment by felixfontein** [comment]
@aarongable @jsha this should fix CI, which is currently broken (see #338). PTAL.

**Review by jsha — APPROVED** [review]
Thanks!

**Comment by felixfontein** [comment]
@jsha thanks for reviewing and merging!

**Pull request merged**
