### PR TITLE
Fix current CI builds

### LINKED ISSUE #349: Fix Travis CI build failures
The project experiences build failures due to building on 1.13.x.

Go 1.14 introduces https://github.com/golang/proposal/blob/master/design/6977-overlapping-interfaces.md which is a feature consumed by a library in the load generator pulled in from letsencrypt/boulder.

From failing build:
```
$ GO111MODULE=off go get github.com/letsencrypt/boulder/test/load-generator
# github.com/letsencrypt/boulder/vendor/go.opentelemetry.io/otel/trace
../boulder/vendor/go.opentelemetry.io/otel/trace/config.go:117:2: duplicate method private
The command "GO111MODULE=off go get github.com/letsencrypt/boulder/test/load-generator" failed and exited with 2 during .
```

Reproducing locally:
```
squizzling@emu:/tank/tank/src/pebble$ /usr/local/go/1.13.5/bin/go get github.com/letsencrypt/boulder/test/load-generator
go: finding github.com/letsencrypt/boulder latest
# go.opentelemetry.io/otel/trace
../../go/pkg/mod/go.opentelemetry.io/otel/trace@v0.19.0/config.go:117:2: duplicate method private
note: module requires Go 1.14

squizzling@emu:/tank/tank/src/pebble$ /usr/local/go/1.14.0/bin/go get github.com/letsencrypt/boulder/test/load-generator
go: found github.com/letsencrypt/boulder/test/load-generator in github.com/letsencrypt/boulder v0.0.0-20210614170818-b5aab2940779
```

### PR DESCRIPTION
**Pull request by squizzling**
While the project build successfully under v1.13, the CI system requires v1.14 due to an external tool that is pulled in.  This should bump everything to 1.16, along with a fresh go mod vendor and go mod tidy.

Might fix #349

### CODE REVIEW

**Comment by squizzling** [comment]
This has revealed further problems causing the build to fail:
- linting errors
- a data race

I'll look in to them tomorrow unless it's picked up in the mean time.

**Comment by squizzling** [comment]
This is now ready for review.  Per https://github.com/letsencrypt/pebble/issues/349#issuecomment-862041495, I went for option 1(+test), as it is the least invasive at this point in time.  I can work on moving the entire memory store (or just the authorization) to be by value, but I believe it should be a dedicated issue.

**Comment by squizzling** [comment]
cc @aarongable, not sure who else to add for reviewers.

**Review by aarongable — COMMENTED** [review]
LGTM! It would be great for either the lock/unlock code to point at the test that breaks if it is removed, or for the test to point at the lock/unlock which prevents the datarace. Otherwise I think the test is a little unclear, in that the comment says that it exercises a specific race condition, but of course it doesn't anymore, thanks to the fix.

**Comment by squizzling** [comment]
Updated comments in commit 17e426fe607237623af4ab376bfbb0ebe1a781b5 to be more explanatory, and indicate when/if they can be removed.

**Review by aarongable — APPROVED** [review]

**Review by jsha — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
